        if 'bearing_winding_conductors_per_slot' not in self.user_input['winding']: self.user_input['winding']['bearing_winding_conductors_per_slot'] = 10
        if 'bearing_winding_current' not in self.user_input['winding']: self.user_input['winding']['bearing_winding_current'] = 0
        if 'drive_winding_conductors_per_slot' not in self.user_input['winding']: self.user_input['winding']['drive_winding_conductors_per_slot'] = 10
        if 'drive_winding_conductors_per_slot' not in self.user_input['winding']: self.user_input['winding']['drive_winding_conductors_per_slot'] = acm_variant.user_input['winding'].get('wires_per_slot', 10
        if 'drive_winding_current' not in self.user_input['winding']: self.user_input['winding']['drive_winding_current'] = 0
        if 'excitation_frequency_simulated' not in self.user_input['winding']: self.user_input['winding']['excitation_frequency_simulated'] = 500
        if 'initial_rotation_angle' not in self.user_input['winding']: self.user_input['winding']['initial_rotation_angle'] = 0.0
        if 'l_stack' not in self.user_input['winding']: self.user_input['winding']['l_stack'] = 16.0
        if 'l_stack' not in self.user_input['winding']: self.user_input['winding']['l_stack'] = None
        if 'machine_class' not in self.user_input['target']: self.user_input['target']['machine_class'] = 'SPMSM'
        if 'magnet_area' not in self.user_input['geometry']: self.user_input['geometry']['magnet_area'] = None
        if 'phase_resistance' not in self.user_input['winding']: self.user_input['winding']['phase_resistance'] = 0.1
        if 'pole_count' not in self.user_input['winding']: self.user_input['winding']['pole_count'] = 10
        if 'r_rotor_outer' not in self.user_input['geometry']: self.user_input['geometry']['r_rotor_outer'] = None
        if 'r_shaft' not in self.user_input['geometry']: self.user_input['geometry']['r_shaft'] = geom.get('r_rotor_inner', None
        if 'r_stator_outer' not in self.user_input['geometry']: self.user_input['geometry']['r_stator_outer'] = None
        if 'rated_power' not in self.user_input['winding']: self.user_input['winding']['rated_power'] = None
        if 'rated_speed' not in self.user_input['winding']: self.user_input['winding']['rated_speed'] = 20000
        if 'rated_speed' not in self.user_input['winding']: self.user_input['winding']['rated_speed'] = wind.get('speed_rpm', None
        if 'rated_speed' not in self.user_input['winding']: self.user_input['winding']['rated_speed'] = wind_dict.get('speed_rpm', None
        if 'slot_count' not in self.user_input['winding']: self.user_input['winding']['slot_count'] = 12
        if 'stator_magnet_area' not in self.user_input['geometry']: self.user_input['geometry']['stator_magnet_area'] = None